on: push
jobs:
  build-node:
    run-on: ubuntu-latest
    container: node:20
    steps:
      - run: node --version
      - run: node --version
      - usese: actions/checkout@v3
      - run: npm install
      - run: node server.js